package a2_1901040115.model;
/*
a1_1901040115.Student name: Ha Thi Ngoc Lan
a1_1901040115.Student id: 1901040115
Class: 1C19
 */

public class Enrolment {
    /* @effects
    An enrolment records a fact that a student has registered interest to study a specific module in a given semester.
    An enrolment contains the following attributes: student, module, internal mark, examination mark and final grade.
    The final grade is generated by the program from an aggregated mark, which is computed from the internal and
    examination marks using the formula: aggregated mark = 0.4 × internal mark + 0.6 × examination mark.

     */
    //attributes
    private Student student;
    private Module module;
    private double internalMark;
    private double examMark;
    private  String finalGrade;

    //constructor
    //a enrolment is initialed without final grade
    public Enrolment(Student student, Module module, double internalMark, double examMark) {
        this.student = student;
        this.module = module;
        this.internalMark = internalMark;
        this.examMark = examMark;
        this.finalGrade = "";
    }
    public Enrolment(Student student, Module module, double internalMark, double examMark, String finalGrade) {
        this.student = student;
        this.module = module;
        this.internalMark = internalMark;
        this.examMark = examMark;
        this.finalGrade = finalGrade;
    }

    //getters and setters
    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Module getModule() {
        return module;
    }

    public void setModule(Module module) {
        this.module = module;
    }

    public double getInternalMark() {
        return internalMark;
    }

    public void setInternalMark(double internalMark) {
        this.internalMark = internalMark;
    }

    public double getExamMark() {
        return examMark;
    }

    public void setExamMark(double examMark) {
        this.examMark = examMark;
    }

    public String getFinalGrade() {
        return finalGrade;
    }

    public void setFinalGrade(String finalGrade){
        this.finalGrade = finalGrade;
    }


}
