package a2_1901040115.model;
/*
Student name: Ha Thi Ngoc Lan
Student id: 1901040115
Class: 1C19
 */


import java.util.ArrayList;
import java.util.List;


public abstract class Module {
    /*
    A module contains following attributes: code, name, semester and credits.
    The module code is a unique module identifier which is generated by the system
     using the formula: the letter “M” followed by the next auto-incremented integer starting from a base.
    There are two types of modules: compulsory module and elective module.
    There are no other types of module.
     */
    private String code;
    private String name;
    private int semester;
    private int credits;



    //constructor
    public Module(String code, String name, int semesterID, int credits) {
        this.code = code;
        this.name = name;
        this.semester = semesterID;
        this.credits = credits;
    }


    //getters and setters
    public String getCode() {
        return code;
    }

    public void setCode(String code){this.code = code;}

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getSemester() {
        return semester;
    }

    public void setSemester(int semester) {
        this.semester = semester;
    }

    public int getCredits() {
        return credits;
    }

    public void setCredits(int credits) {
        this.credits = credits;
    }


}
